version: '1.0'
services:
  adminer:
    image: adminer
    hostname: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  minio:
    image: minio/minio
    container_name: minio-container
    hostname: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    volumes:
      - ./data-minio:/data
  postgres:
    image: postgres
    container_name: postgres-container
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperless
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
  paperless_rest_service:
    build: ./paperless_rest_service
    container_name: paperless_rest_service
    hostname: paperless_rest_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/paperless
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  paperless_ocr_service:
    build: ./paperless_ocr_service
    container_name: paperless_ocr_service
    hostname: paperless_ocr_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/paperless
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch-container:latest
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  elasticsearch-ui:
    image: appbaseio/dejavu:latest
    container_name: elasticsearch-ui-container
    hostname: elasticsearch-ui
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-container:9200
networks:
  swkom3:
    driver: bridge